monster_list = [
    "list is one-indexed",
    "giant ant",
    "killer bee",
    "soldier ant",
    "fire ant",
    "giant beetle",
    "queen bee",
    "acid blob",
    "quivering blob",
    "gelatinous cube",
    "chickatrice",
    "cockatrice",
    "pyrolisk",
    "jackal",
    "fox",
    "coyote",
    "werejackal",
    "little dog",
    "dog",
    "large dog",
    "dingo",
    "wolf",
    "werewolf",
    "warg",
    "winter wolf cub",
    "winter wolf",
    "hell hound pup",
    "hell hound",
    "Cerberus",
    "gas spore",
    "floating eye",
    "freezing sphere",
    "flaming sphere",
    "shocking sphere",
    "kitten",
    "housecat",
    "jaguar",
    "lynx",
    "panther",
    "large cat",
    "tiger",
    "gremlin",
    "gargoyle",
    "winged gargoyle",
    "hobbit",
    "dwarf",
    "bugbear",
    "dwarf lord",
    "dwarf king",
    "mind flayer",
    "master mind flayer",
    "manes",
    "homunculus",
    "imp",
    "lemure",
    "quasit",
    "tengu",
    "blue jelly",
    "spotted jelly",
    "ochre jelly",
    "kobold",
    "large kobold",
    "kobold lord",
    "kobold shaman",
    "leprechaun",
    "small mimic",
    "large mimic",
    "giant mimic",
    "wood nymph",
    "water nymph",
    "mountain nymph",
    "goblin",
    "hobgoblin",
    "orc",
    "hill orc",
    "Mordor orc",
    "Uruk-hai",
    "orc shaman",
    "orc-captain",
    "rock piercer",
    "iron piercer",
    "glass piercer",
    "rothe",
    "mumak",
    "leocrotta",
    "wumpus",
    "titanothere",
    "baluchitherium",
    "mastodon",
    "sewer rat",
    "giant rat",
    "rabid rat",
    "wererat",
    "rock mole",
    "woodchuck",
    "cave spider",
    "centipede",
    "giant spider",
    "scorpion",
    "lurker above",
    "trapper",
    "white unicorn",
    "gray unicorn",
    "black unicorn",
    "pony",
    "horse",
    "warhorse",
    "fog cloud",
    "dust vortex",
    "ice vortex",
    "energy vortex",
    "steam vortex",
    "fire vortex",
    "baby long worm",
    "baby purple worm",
    "long worm",
    "purple worm",
    "grid bug",
    "xan",
    "yellow light",
    "black light",
    "zruty",
    "couatl",
    "Aleax",
    "Angel",
    "ki-rin",
    "Archon",
    "bat",
    "giant bat",
    "raven",
    "vampire bat",
    "plains centaur",
    "forest centaur",
    "mountain centaur",
    "baby gray dragon",
    "baby silver dragon",
    "baby red dragon",
    "baby white dragon",
    "baby orange dragon",
    "baby black dragon",
    "baby blue dragon",
    "baby green dragon",
    "baby yellow dragon",
    "gray dragon",
    "silver dragon",
    "red dragon",
    "white dragon",
    "orange dragon",
    "black dragon",
    "blue dragon",
    "green dragon",
    "yellow dragon",
    "stalker",
    "air elemental",
    "fire elemental",
    "earth elemental",
    "water elemental",
    "lichen",
    "brown mold",
    "yellow mold",
    "green mold",
    "red mold",
    "shrieker",
    "violet fungus",
    "gnome",
    "gnome lord",
    "gnomish wizard",
    "gnome king",
    "giant",
    "stone giant",
    "hill giant",
    "fire giant",
    "frost giant",
    "storm giant",
    "ettin",
    "titan",
    "minotaur",
    "jabberwock",
    "Keystone Kop",
    "Kop Sergeant",
    "Kop Lieutenant",
    "Kop Kaptain",
    "lich",
    "demilich",
    "master lich",
    "arch-lich",
    "kobold mummy",
    "gnome mummy",
    "orc mummy",
    "dwarf mummy",
    "elf mummy",
    "human mummy",
    "ettin mummy",
    "giant mummy",
    "red naga hatchling",
    "black naga hatchling",
    "golden naga hatchling",
    "guardian naga hatchling",
    "red naga",
    "black naga",
    "golden naga",
    "guardian naga",
    "ogre",
    "ogre lord",
    "ogre king",
    "gray ooze",
    "brown pudding",
    "black pudding",
    "green slime",
    "quantum mechanic",
    "rust monster",
    "disenchanter",
    "garter snake",
    "snake",
    "water moccasin",
    "pit viper",
    "python",
    "cobra",
    "troll",
    "ice troll",
    "rock troll",
    "water troll",
    "Olog-hai",
    "umber hulk",
    "vampire",
    "vampire lord",
    "Vlad the Impaler",
    "barrow wight",
    "wraith",
    "Nazgul",
    "ghost",
    "shade",
    "xorn",
    "monkey",
    "ape",
    "owlbear",
    "yeti",
    "carnivorous ape",
    "sasquatch",
    "kobold zombie",
    "gnome zombie",
    "orc zombie",
    "dwarf zombie",
    "elf zombie",
    "human zombie",
    "ettin zombie",
    "giant zombie",
    "ghoul",
    "skeleton",
    "straw golem",
    "paper golem",
    "rope golem",
    "gold golem",
    "leather golem",
    "wood golem",
    "flesh golem",
    "clay golem",
    "stone golem",
    "glass golem",
    "iron golem",
    "human",
    "wererat",
    "werejackal",
    "werewolf",
    "elf",
    "Woodland-elf",
    "Green-elf",
    "Grey-elf",
    "elf-lord",
    "Elvenking",
    "doppelganger",
    "nurse",
    "shopkeeper",
    "guard",
    "prisoner",
    "Oracle",
    "aligned priest",
    "high priest",
    "soldier",
    "sergeant",
    "lieutenant",
    "captain",
    "watchman",
    "watch captain",
    "Medusa",
    "Wizard of Yendor",
    "Croesus",
    "Charon",
    "water demon",
    "horned devil",
    "succubus",
    "incubus",
    "erinys",
    "barbed devil",
    "marilith",
    "vrock",
    "hezrou",
    "bone devil",
    "ice devil",
    "nalfeshnee",
    "pit fiend",
    "balrog",
    "Juiblex",
    "Yeenoghu",
    "Orcus",
    "Geryon",
    "Dispater",
    "Baalzebub",
    "Asmodeus",
    "Demogorgon",
    "Death",
    "Pestilence",
    "Famine",
    "djinni",
    "sandestin",
    "jellyfish",
    "piranha",
    "shark",
    "giant eel",
    "electric eel",
    "kraken",
    "newt",
    "gecko",
    "iguana",
    "baby crocodile",
    "lizard",
    "chameleon",
    "crocodile",
    "salamander",
    "long worm tail",
    "archeologist",
    "barbarian",
    "caveman",
    "cavewoman",
    "healer",
    "knight",
    "monk",
    "priest",
    "priestess",
    "ranger",
    "rogue",
    "samurai",
    "tourist",
    "valkyrie",
    "wizard",
    "Lord Carnarvon",
    "Pelias",
    "Shaman Karnov",
    "Hippocrates",
    "King Arthur",
    "Grand Master",
    "Arch Priest",
    "Orion",
    "Master of Thieves",
    "Lord Sato",
    "Twoflower",
    "Norn",
    "Neferet the Green",
    "Minion of Huhetotl",
    "Thoth Amon",
    "Chromatic Dragon",
    "Cyclops",
    "Ixoth",
    "Master Kaen",
    "Nalzok",
    "Scorpius",
    "Master Assassin",
    "Ashikaga Takauji",
    "Lord Surtur",
    "Dark One",
    "student",
    "chieftain",
    "neanderthal",
    "attendant",
    "page",
    "abbot",
    "acolyte",
    "hunter",
    "thug",
    "ninja",
    "roshi",
    "guide",
    "warrior",
    "apprentice",
    "",
]
monsters = {
    "giant ant": "S_ANT",
    "killer bee": "S_ANT",
    "soldier ant": "S_ANT",
    "fire ant": "S_ANT",
    "giant beetle": "S_ANT",
    "queen bee": "S_ANT",
    "acid blob": "S_BLOB",
    "quivering blob": "S_BLOB",
    "gelatinous cube": "S_BLOB",
    "chickatrice": "S_COCKATRICE",
    "cockatrice": "S_COCKATRICE",
    "pyrolisk": "S_COCKATRICE",
    "jackal": "S_DOG",
    "fox": "S_DOG",
    "coyote": "S_DOG",
    "werejackal": "S_DOG",
    "little dog": "S_DOG",
    "dog": "S_DOG",
    "large dog": "S_DOG",
    "dingo": "S_DOG",
    "wolf": "S_DOG",
    "werewolf": "S_DOG",
    "warg": "S_DOG",
    "winter wolf cub": "S_DOG",
    "winter wolf": "S_DOG",
    "hell hound pup": "S_DOG",
    "hell hound": "S_DOG",
    "Cerberus": "S_DOG",
    "gas spore": "S_EYE",
    "floating eye": "S_EYE",
    "freezing sphere": "S_EYE",
    "flaming sphere": "S_EYE",
    "shocking sphere": "S_EYE",
    "kitten": "S_FELINE",
    "housecat": "S_FELINE",
    "jaguar": "S_FELINE",
    "lynx": "S_FELINE",
    "panther": "S_FELINE",
    "large cat": "S_FELINE",
    "tiger": "S_FELINE",
    "gremlin": "S_GREMLIN",
    "gargoyle": "S_GREMLIN",
    "winged gargoyle": "S_GREMLIN",
    "hobbit": "S_HUMANOID",
    "dwarf": "S_HUMANOID",
    "bugbear": "S_HUMANOID",
    "dwarf lord": "S_HUMANOID",
    "dwarf king": "S_HUMANOID",
    "mind flayer": "S_HUMANOID",
    "master mind flayer": "S_HUMANOID",
    "manes": "S_IMP",
    "homunculus": "S_IMP",
    "imp": "S_IMP",
    "lemure": "S_IMP",
    "quasit": "S_IMP",
    "tengu": "S_IMP",
    "blue jelly": "S_JELLY",
    "spotted jelly": "S_JELLY",
    "ochre jelly": "S_JELLY",
    "kobold": "S_KOBOLD",
    "large kobold": "S_KOBOLD",
    "kobold lord": "S_KOBOLD",
    "kobold shaman": "S_KOBOLD",
    "leprechaun": "S_LEPRECHAUN",
    "small mimic": "S_MIMIC",
    "large mimic": "S_MIMIC",
    "giant mimic": "S_MIMIC",
    "wood nymph": "S_NYMPH",
    "water nymph": "S_NYMPH",
    "mountain nymph": "S_NYMPH",
    "goblin": "S_ORC",
    "hobgoblin": "S_ORC",
    "orc": "S_ORC",
    "hill orc": "S_ORC",
    "Mordor orc": "S_ORC",
    "Uruk-hai": "S_ORC",
    "orc shaman": "S_ORC",
    "orc-captain": "S_ORC",
    "rock piercer": "S_PIERCER",
    "iron piercer": "S_PIERCER",
    "glass piercer": "S_PIERCER",
    "rothe": "S_QUADRUPED",
    "mumak": "S_QUADRUPED",
    "leocrotta": "S_QUADRUPED",
    "wumpus": "S_QUADRUPED",
    "titanothere": "S_QUADRUPED",
    "baluchitherium": "S_QUADRUPED",
    "mastodon": "S_QUADRUPED",
    "sewer rat": "S_RODENT",
    "giant rat": "S_RODENT",
    "rabid rat": "S_RODENT",
    "wererat": "S_RODENT",
    "rock mole": "S_RODENT",
    "woodchuck": "S_RODENT",
    "cave spider": "S_SPIDER",
    "centipede": "S_SPIDER",
    "giant spider": "S_SPIDER",
    "scorpion": "S_SPIDER",
    "lurker above": "S_TRAPPER",
    "trapper": "S_TRAPPER",
    "white unicorn": "S_UNICORN",
    "gray unicorn": "S_UNICORN",
    "black unicorn": "S_UNICORN",
    "pony": "S_UNICORN",
    "horse": "S_UNICORN",
    "warhorse": "S_UNICORN",
    "fog cloud": "S_VORTEX",
    "dust vortex": "S_VORTEX",
    "ice vortex": "S_VORTEX",
    "energy vortex": "S_VORTEX",
    "steam vortex": "S_VORTEX",
    "fire vortex": "S_VORTEX",
    "baby long worm": "S_WORM",
    "baby purple worm": "S_WORM",
    "long worm": "S_WORM",
    "purple worm": "S_WORM",
    "grid bug": "S_XAN",
    "xan": "S_XAN",
    "yellow light": "S_LIGHT",
    "black light": "S_LIGHT",
    "zruty": "S_ZRUTY",
    "couatl": "S_ANGEL",
    "Aleax": "S_ANGEL",
    "Angel": "S_ANGEL",
    "ki-rin": "S_ANGEL",
    "Archon": "S_ANGEL",
    "bat": "S_BAT",
    "giant bat": "S_BAT",
    "raven": "S_BAT",
    "vampire bat": "S_BAT",
    "plains centaur": "S_CENTAUR",
    "forest centaur": "S_CENTAUR",
    "mountain centaur": "S_CENTAUR",
    "baby gray dragon": "S_DRAGON",
    "baby silver dragon": "S_DRAGON",
    "baby red dragon": "S_DRAGON",
    "baby white dragon": "S_DRAGON",
    "baby orange dragon": "S_DRAGON",
    "baby black dragon": "S_DRAGON",
    "baby blue dragon": "S_DRAGON",
    "baby green dragon": "S_DRAGON",
    "baby yellow dragon": "S_DRAGON",
    "gray dragon": "S_DRAGON",
    "silver dragon": "S_DRAGON",
    "red dragon": "S_DRAGON",
    "white dragon": "S_DRAGON",
    "orange dragon": "S_DRAGON",
    "black dragon": "S_DRAGON",
    "blue dragon": "S_DRAGON",
    "green dragon": "S_DRAGON",
    "yellow dragon": "S_DRAGON",
    "stalker": "S_ELEMENTAL",
    "air elemental": "S_ELEMENTAL",
    "fire elemental": "S_ELEMENTAL",
    "earth elemental": "S_ELEMENTAL",
    "water elemental": "S_ELEMENTAL",
    "lichen": "S_FUNGUS",
    "brown mold": "S_FUNGUS",
    "yellow mold": "S_FUNGUS",
    "green mold": "S_FUNGUS",
    "red mold": "S_FUNGUS",
    "shrieker": "S_FUNGUS",
    "violet fungus": "S_FUNGUS",
    "gnome": "S_GNOME",
    "gnome lord": "S_GNOME",
    "gnomish wizard": "S_GNOME",
    "gnome king": "S_GNOME",
    "giant": "S_GIANT",
    "stone giant": "S_GIANT",
    "hill giant": "S_GIANT",
    "fire giant": "S_GIANT",
    "frost giant": "S_GIANT",
    "storm giant": "S_GIANT",
    "ettin": "S_GIANT",
    "titan": "S_GIANT",
    "minotaur": "S_GIANT",
    "jabberwock": "S_JABBERWOCK",
    "Keystone Kop": "S_KOP",
    "Kop Sergeant": "S_KOP",
    "Kop Lieutenant": "S_KOP",
    "Kop Kaptain": "S_KOP",
    "lich": "S_LICH",
    "demilich": "S_LICH",
    "master lich": "S_LICH",
    "arch-lich": "S_LICH",
    "kobold mummy": "S_MUMMY",
    "gnome mummy": "S_MUMMY",
    "orc mummy": "S_MUMMY",
    "dwarf mummy": "S_MUMMY",
    "elf mummy": "S_MUMMY",
    "human mummy": "S_MUMMY",
    "ettin mummy": "S_MUMMY",
    "giant mummy": "S_MUMMY",
    "red naga hatchling": "S_NAGA",
    "black naga hatchling": "S_NAGA",
    "golden naga hatchling": "S_NAGA",
    "guardian naga hatchling": "S_NAGA",
    "red naga": "S_NAGA",
    "black naga": "S_NAGA",
    "golden naga": "S_NAGA",
    "guardian naga": "S_NAGA",
    "ogre": "S_OGRE",
    "ogre lord": "S_OGRE",
    "ogre king": "S_OGRE",
    "gray ooze": "S_PUDDING",
    "brown pudding": "S_PUDDING",
    "black pudding": "S_PUDDING",
    "green slime": "S_PUDDING",
    "quantum mechanic": "S_QUANTMECH",
    "rust monster": "S_RUSTMONST",
    "disenchanter": "S_RUSTMONST",
    "garter snake": "S_SNAKE",
    "snake": "S_SNAKE",
    "water moccasin": "S_SNAKE",
    "pit viper": "S_SNAKE",
    "python": "S_SNAKE",
    "cobra": "S_SNAKE",
    "troll": "S_TROLL",
    "ice troll": "S_TROLL",
    "rock troll": "S_TROLL",
    "water troll": "S_TROLL",
    "Olog-hai": "S_TROLL",
    "umber hulk": "S_UMBER",
    "vampire": "S_VAMPIRE",
    "vampire lord": "S_VAMPIRE",
    "Vlad the Impaler": "S_VAMPIRE",
    "barrow wight": "S_WRAITH",
    "wraith": "S_WRAITH",
    "Nazgul": "S_WRAITH",
    "ghost": "S_WRAITH",
    "shade": "S_WRAITH",
    "xorn": "S_XORN",
    "monkey": "S_YETI",
    "ape": "S_YETI",
    "owlbear": "S_YETI",
    "yeti": "S_YETI",
    "carnivorous ape": "S_YETI",
    "sasquatch": "S_YETI",
    "kobold zombie": "S_ZOMBIE",
    "gnome zombie": "S_ZOMBIE",
    "orc zombie": "S_ZOMBIE",
    "dwarf zombie": "S_ZOMBIE",
    "elf zombie": "S_ZOMBIE",
    "human zombie": "S_ZOMBIE",
    "ettin zombie": "S_ZOMBIE",
    "giant zombie": "S_ZOMBIE",
    "ghoul": "S_ZOMBIE",
    "skeleton": "S_ZOMBIE",
    "straw golem": "S_GOLEM",
    "paper golem": "S_GOLEM",
    "rope golem": "S_GOLEM",
    "gold golem": "S_GOLEM",
    "leather golem": "S_GOLEM",
    "wood golem": "S_GOLEM",
    "flesh golem": "S_GOLEM",
    "clay golem": "S_GOLEM",
    "stone golem": "S_GOLEM",
    "glass golem": "S_GOLEM",
    "iron golem": "S_GOLEM",
    "human": "S_HUMAN",
    "wererat": "S_HUMAN",
    "werejackal": "S_HUMAN",
    "werewolf": "S_HUMAN",
    "elf": "S_HUMAN",
    "Woodland-elf": "S_HUMAN",
    "Green-elf": "S_HUMAN",
    "Grey-elf": "S_HUMAN",
    "elf-lord": "S_HUMAN",
    "Elvenking": "S_HUMAN",
    "doppelganger": "S_HUMAN",
    "nurse": "S_HUMAN",
    "shopkeeper": "S_HUMAN",
    "guard": "S_HUMAN",
    "prisoner": "S_HUMAN",
    "Oracle": "S_HUMAN",
    "aligned priest": "S_HUMAN",
    "high priest": "S_HUMAN",
    "soldier": "S_HUMAN",
    "sergeant": "S_HUMAN",
    "lieutenant": "S_HUMAN",
    "captain": "S_HUMAN",
    "watchman": "S_HUMAN",
    "watch captain": "S_HUMAN",
    "Medusa": "S_HUMAN",
    "Wizard of Yendor": "S_HUMAN",
    "Croesus": "S_HUMAN",
    "Charon": "S_HUMAN",
    "water demon": "S_DEMON",
    "horned devil": "S_DEMON",
    "succubus": "S_DEMON",
    "incubus": "S_DEMON",
    "erinys": "S_DEMON",
    "barbed devil": "S_DEMON",
    "marilith": "S_DEMON",
    "vrock": "S_DEMON",
    "hezrou": "S_DEMON",
    "bone devil": "S_DEMON",
    "ice devil": "S_DEMON",
    "nalfeshnee": "S_DEMON",
    "pit fiend": "S_DEMON",
    "balrog": "S_DEMON",
    "Juiblex": "S_DEMON",
    "Yeenoghu": "S_DEMON",
    "Orcus": "S_DEMON",
    "Geryon": "S_DEMON",
    "Dispater": "S_DEMON",
    "Baalzebub": "S_DEMON",
    "Asmodeus": "S_DEMON",
    "Demogorgon": "S_DEMON",
    "Death": "S_DEMON",
    "Pestilence": "S_DEMON",
    "Famine": "S_DEMON",
    "djinni": "S_DEMON",
    "sandestin": "S_DEMON",
    "jellyfish": "S_EEL",
    "piranha": "S_EEL",
    "shark": "S_EEL",
    "giant eel": "S_EEL",
    "electric eel": "S_EEL",
    "kraken": "S_EEL",
    "newt": "S_LIZARD",
    "gecko": "S_LIZARD",
    "iguana": "S_LIZARD",
    "baby crocodile": "S_LIZARD",
    "lizard": "S_LIZARD",
    "chameleon": "S_LIZARD",
    "crocodile": "S_LIZARD",
    "salamander": "S_LIZARD",
    "long worm tail": "S_WORM_TAIL",
    "archeologist": "S_HUMAN",
    "barbarian": "S_HUMAN",
    "caveman": "S_HUMAN",
    "cavewoman": "S_HUMAN",
    "healer": "S_HUMAN",
    "knight": "S_HUMAN",
    "monk": "S_HUMAN",
    "priest": "S_HUMAN",
    "priestess": "S_HUMAN",
    "ranger": "S_HUMAN",
    "rogue": "S_HUMAN",
    "samurai": "S_HUMAN",
    "tourist": "S_HUMAN",
    "valkyrie": "S_HUMAN",
    "wizard": "S_HUMAN",
    "Lord Carnarvon": "S_HUMAN",
    "Pelias": "S_HUMAN",
    "Shaman Karnov": "S_HUMAN",
    "Hippocrates": "S_HUMAN",
    "King Arthur": "S_HUMAN",
    "Grand Master": "S_HUMAN",
    "Arch Priest": "S_HUMAN",
    "Orion": "S_HUMAN",
    "Master of Thieves": "S_HUMAN",
    "Lord Sato": "S_HUMAN",
    "Twoflower": "S_HUMAN",
    "Norn": "S_HUMAN",
    "Neferet the Green": "S_HUMAN",
    "Minion of Huhetotl": "S_DEMON",
    "Thoth Amon": "S_HUMAN",
    "Chromatic Dragon": "S_DRAGON",
    "Cyclops": "S_GIANT",
    "Ixoth": "S_DRAGON",
    "Master Kaen": "S_HUMAN",
    "Nalzok": "S_DEMON",
    "Scorpius": "S_SPIDER",
    "Master Assassin": "S_HUMAN",
    "Ashikaga Takauji": "S_HUMAN",
    "Lord Surtur": "S_GIANT",
    "Dark One": "S_HUMAN",
    "student": "S_HUMAN",
    "chieftain": "S_HUMAN",
    "neanderthal": "S_HUMAN",
    "attendant": "S_HUMAN",
    "page": "S_HUMAN",
    "abbot": "S_HUMAN",
    "acolyte": "S_HUMAN",
    "hunter": "S_HUMAN",
    "thug": "S_HUMAN",
    "ninja": "S_HUMAN",
    "roshi": "S_HUMAN",
    "guide": "S_HUMAN",
    "warrior": "S_HUMAN",
    "apprentice": "S_HUMAN",
    "": "0",
}
monster_syms = {
    "S_ANT": 'a',
    "S_BLOB": 'b',
    "S_COCKATRICE": 'c',
    "S_DOG": 'd',
    "S_EYE": 'e',
    "S_FELINE": 'f',
    "S_GREMLIN": 'g',
    "S_HUMANOID": 'h',
    "S_IMP": 'i',
    "S_JELLY": 'j',
    "S_KOBOLD": 'k',
    "S_LEPRECHAUN": 'l',
    "S_MIMIC": 'm',
    "S_NYMPH": 'n',
    "S_ORC": 'o',
    "S_PIERCER": 'p',
    "S_QUADRUPED": 'q',
    "S_RODENT": 'r',
    "S_SPIDER": 's',
    "S_TRAPPER": 't',
    "S_UNICORN": 'u',
    "S_VORTEX": 'v',
    "S_WORM": 'w',
    "S_XAN": 'x',
    "S_LIGHT": 'y',
    "S_ZRUTY": 'z',
    "S_ANGEL": 'A',
    "S_BAT": 'B',
    "S_CENTAUR": 'C',
    "S_DRAGON": 'D',
    "S_ELEMENTAL": 'E',
    "S_FUNGUS": 'F',
    "S_GNOME": 'G',
    "S_GIANT": 'H',
    "S_JABBERWOCK": 'J',
    "S_KOP": 'K',
    "S_LICH": 'L',
    "S_MUMMY": 'M',
    "S_NAGA": 'N',
    "S_OGRE": 'O',
    "S_PUDDING": 'P',
    "S_QUANTMECH": 'Q',
    "S_RUSTMONST": 'R',
    "S_SNAKE": 'S',
    "S_TROLL": 'T',
    "S_UMBER": 'U',
    "S_VAMPIRE": 'V',
    "S_WRAITH": 'W',
    "S_XORN": 'X',
    "S_YETI": 'Y',
    "S_ZOMBIE": 'Z',
    "S_HUMAN": '@',
    "S_GHOST": '": ',
    "S_GOLEM": '\'',
    "S_DEMON": '&',
    "S_EEL": ';',
    "S_LIZARD": ':',
    "S_INVISIBLE": 'I',
    "S_WORM_TAIL": '~',
    "S_MIMIC_DEF": ']',
}
def lookup_monster(number):
    monster = monster_list[number]
    return "{0} ({1})".format(monster_syms[monsters[monster]], monster)
